name: clang-format

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          clang-format -version
          clang-format -style=Google -i $(find . -type f -name "*.c" -or -name "*.h")

      - name: Commit formatted files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Format code using clang-format" || true
          git push --set-upstream origin ${{ github.ref }}:${{ github.ref }} --force-with-lease --quiet
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
